# Generated by Django 4.0.6 on 2022-07-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdbid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('img', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmbid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('img', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecastInst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recast.actor')),
                ('downvotes', models.ManyToManyField(related_name='rcdownvotes', to='recast.user')),
                ('recast', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recast.recast')),
                ('upvotes', models.ManyToManyField(related_name='rcupvotes', to='recast.user')),
            ],
        ),
        migrations.AddField(
            model_name='recast',
            name='downvotes',
            field=models.ManyToManyField(related_name='downvotes', to='recast.user'),
        ),
        migrations.AddField(
            model_name='recast',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recast.movie'),
        ),
        migrations.AddField(
            model_name='recast',
            name='upvotes',
            field=models.ManyToManyField(related_name='upvotes', to='recast.user'),
        ),
        migrations.AddField(
            model_name='recast',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recast.user'),
        ),
        migrations.CreateModel(
            name='CastInst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recast.actor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recast.movie')),
            ],
        ),
    ]
