# Generated by Django 4.0.6 on 2022-07-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='img',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='actor',
            name='tmdbid',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='castinst',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tmbid',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='recast',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='recastinst',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
