# Generated by Django 4.0.6 on 2022-07-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recast', '0002_alter_actor_img_alter_actor_name_alter_actor_tmdbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recast',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to='recast.user'),
        ),
        migrations.AlterField(
            model_name='recast',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='recast.user'),
        ),
        migrations.AlterField(
            model_name='recastinst',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='rcdownvotes', to='recast.user'),
        ),
        migrations.AlterField(
            model_name='recastinst',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='rcupvotes', to='recast.user'),
        ),
    ]
