# Generated by Django 4.0.6 on 2022-07-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recast', '0003_alter_recast_downvotes_alter_recast_upvotes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tmbid',
            new_name='tmdbid',
        ),
    ]
