# Generated by Django 4.0.6 on 2022-07-18 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recast', '0004_rename_tmbid_movie_tmdbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castinst',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='castInst', to='recast.actor'),
        ),
        migrations.AlterField(
            model_name='castinst',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='castInst', to='recast.movie'),
        ),
        migrations.AlterField(
            model_name='recast',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recast', to='recast.movie'),
        ),
        migrations.AlterField(
            model_name='recast',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recast', to='recast.user'),
        ),
        migrations.AlterField(
            model_name='recastinst',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recastInst', to='recast.actor'),
        ),
        migrations.AlterField(
            model_name='recastinst',
            name='recast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recastInst', to='recast.recast'),
        ),
    ]
