# Generated by Django 4.0.6 on 2022-07-22 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recast', '0010_alter_recast_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recast',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recasts', to='recast.user'),
        ),
    ]
